#!/bin/bash
# ./configure - Prepares the build environment for Nagios Telegram Bot

set -euo pipefail

# --- Default Paths ---
PREFIX="/usr/local"
BINDIR="${PREFIX}/bin"
SYSCONFDIR="/etc/nagios-telegram-bot"
SYSTEMDDIR="/etc/systemd/system"
NAGIOSDIR="/usr/local/nagios"

# --- Default Config Vars ---
TELEGRAM_BOT_TOKEN=""
ALLOWED_CHAT_IDS=""
NAGIOS_URL=""
NAGIOS_USER=""
NAGIOS_PASS=""
NAGIOS_GROUP="nagios"
DAEMON_USER="nagios-telegram-bot"

# --- Help Menu ---
usage() {
    cat <<EOF
Usage: $0 [OPTION]...

Installation directories:
  --prefix=PREFIX         Install architecture-independent files in PREFIX [$PREFIX]
  --bindir=DIR            User executables [$BINDIR]
  --sysconfdir=DIR        Read-only single-machine data [$SYSCONFDIR]
  --systemddir=DIR        Systemd unit files [$SYSTEMDDIR]
  --nagiosdir=URL         Nagios files [$NAGIOSDIR]

Configuration options:
  --bot-token=TOKEN       Telegram Bot Token
  --chat-ids=IDS          Comma-separated allowed Chat IDs
  --nagios-url=URL        Nagios API URL
  --nagios-user=USER      Nagios API Username
  --nagios-pass=PASS      Nagios API Password
  --daemon-user=USER      System user to run the service [$DAEMON_USER]
  --nagios-group=GROUP    Nagios group [$NAGIOS_GROUP]
  --help                  Display this help and exit
EOF
    exit 0
}

# --- Parse Arguments ---
for arg in "$@"; do
    case "$arg" in
        --prefix=*) PREFIX="${arg#*=}" ;;
        --bindir=*) BINDIR="${arg#*=}" ;;
        --sysconfdir=*) SYSCONFDIR="${arg#*=}" ;;
        --systemddir=*) SYSTEMDDIR="${arg#*=}" ;;
        --nagiosdir=*) NAGIOSDIR="${arg#*=}" ;;
        --nagios-group=*) NAGIOS_GROUP="${arg#*=}" ;;
        --bot-token=*) TELEGRAM_BOT_TOKEN="${arg#*=}" ;;
        --chat-ids=*) ALLOWED_CHAT_IDS="${arg#*=}" ;;
        --nagios-url=*) NAGIOS_URL="${arg#*=}" ;;
        --nagios-user=*) NAGIOS_USER="${arg#*=}" ;;
        --nagios-pass=*) NAGIOS_PASS="${arg#*=}" ;;
        --daemon-user=*) DAEMON_USER="${arg#*=}" ;;
        --help) usage ;;
        *) echo "[ERROR] Unknown option: $arg" >&2; exit 1 ;;
    esac
done

echo "[INFO] Checking dependencies..."
DEPENDENCIES=("curl" "jq" "awk" "install")
for cmd in "${DEPENDENCIES[@]}"; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "[FATAL] Required dependency '$cmd' is not installed." >&2
        exit 1
    fi
done
echo "[OK] All dependencies met."

echo ""
echo "[INFO] Gathering configuration data..."
[[ -z "$TELEGRAM_BOT_TOKEN" ]] && read -p "Telegram Bot Token: " TELEGRAM_BOT_TOKEN
[[ -z "$ALLOWED_CHAT_IDS" ]] && read -p "Allowed Chat IDs (comma-separated): " ALLOWED_CHAT_IDS
[[ -z "$NAGIOS_URL" ]] && read -p "Nagios URL (e.g., https://nagios.domain.com/nagios/): " NAGIOS_URL
[[ -z "$NAGIOS_USER" ]] && read -p "Nagios API Username: " NAGIOS_USER
[[ -z "$NAGIOS_PASS" ]] && read -s -p "Nagios API Password: " NAGIOS_PASS
[[ -z "$NAGIOS_GROUP" ]] && read -p "Nagios Group: " NAGIOS_GROUP
[[ -z "$DAEMON_USER" ]] && read -s -p "System user: " DAEMON_USER
echo -e "\n"

# --- Generate Build Files ---
echo "[INFO] Generating configuration files..."
mkdir build

# 1. Generate config.env
cat <<EOF > build/config.env.build
# Generated by ./configure
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
ALLOWED_CHAT_IDS="${ALLOWED_CHAT_IDS}"
NAGIOS_URL="${NAGIOS_URL%/}"
NAGIOS_USER="${NAGIOS_USER}"
NAGIOS_PASS="${NAGIOS_PASS}"
ALERTS_PER_MESSAGE=10
EOF

# 2. Generate Systemd Unit
cat <<EOF > build/nagios-telegram-bot.service.build
[Unit]
Description=Nagios Telegram Bot Interface
After=network.target

[Service]
Type=simple
ExecStart=${BINDIR}/nagios-telegram-bot --config ${SYSCONFDIR}/config.env
Restart=always
RestartSec=10
User=${DAEMON_USER}

[Install]
WantedBy=multi-user.target
EOF

# 3. Generate config.mk for the Makefile
cat <<EOF > build/config.mk
# Generated by ./configure
BINDIR=${BINDIR}
SYSCONFDIR=${SYSCONFDIR}
SYSTEMDDIR=${SYSTEMDDIR}
NAGIOSDIR=${NAGIOSDIR}
DAEMON_USER=${DAEMON_USER}
NAGIOS_GROUP=${NAGIOS_GROUP}
EOF

echo "[OK] Configuration complete."
echo "Type 'make' to install the software."